### ISSUE TITLE
[repo] No .env.example file

### ISSUE THREAD

**Issue by ImJustToNy** [kpostekk/caats#28]
Hi, this repo does not contain any .env.example file for potential contributors to use.
I wanted to run the project locally out of `compose.yml`, but [it requires the `.env` file to run](https://github.com/kpostekk/caats/blob/e19e88e9a64e81bd69cbeb596a966b366a278138/compose.yml#L18). I would love to help you with that, unfortunately, I have no clue what this file shall contain. It makes it harder for people to contribute.

Thank you for reading and keep up with this awesome project!

**Comment by kpostekk** [comment]
For deploying app on docker, a .env file should contains following variables
```
GOOGLE_CLIENT_ID= # OAuth client id, should be obtained from google cloud console
GOOGLE_SECRET= # OAuth scecret, should be obtained from google cloud console
JWT_SECRET=someRandomString # I suggest to use node > randomBytes(128).digest('base64url')
BASE_URL=https://caats.app
```

**Comment by kpostekk** [comment]
https://developers.google.com/identity/protocols/oauth2#1.-obtain-oauth-2.0-credentials-from-the-dynamic_data.setvar.console_name-.

**Comment by ImJustToNy** [comment]
Thanks!
