### ISSUE TITLE
[nest/schedule] not updated English lessons

### ISSUE THREAD

**Issue by OlekZima** [kpostekk/caats#32]
My group (119l, 4 sem) have changed english lessons, but on caats i can not see this

![Screenshot_2023-03-11-13-15-28-146_com.android.chrome.jpg](https://user-images.githubusercontent.com/88747287/224483901-5dd061e9-94ae-44d0-abbf-d9be776b5470.jpg)

![Screenshot_2023-03-11-13-15-59-272_com.android.chrome.jpg](https://user-images.githubusercontent.com/88747287/224483905-f232815f-f9f3-4a05-9acf-8ee7c1cab121.jpg)

**Comment by OlekZima** [comment]
fixed by it's own

**Comment by kpostekk** [comment]
*nature of reverse engineered software*

My guess it was updated/fixed by scraper, it could have some weird hickup. The service was restarted while applying patch for #31, so that could fix that.

**Comment by OlekZima** [comment]
make the blocks wider -- fixed lessons scrapping. Nice
