### ISSUE TITLE
[app/ux][app/search] Ideas and quality of life improvments

### ISSUE THREAD

**Issue by serafinski** [kpostekk/caats#34]
Co dodać:
- kliknięcie logo przenosi do kokpitu (https://caats.app/app) -> _imo warto dodać przynajmniej na mobilce_
![image](https://user-images.githubusercontent.com/88508650/226215454-a13cf6c0-a24f-4326-86ce-1a9db7ab633f.png)

- dodanie opcji filtrowania _(głównym problemem jest niechronologiczne układanie rekordów — np. po dacie jak w ss poniżej)_
![image](https://user-images.githubusercontent.com/88508650/226215652-a6fa2623-0b24-4cca-ba80-27a14a298cb0.png)

Poprawki:
- ew. dodanie opcji zmieniania aktualnych grup w ustawieniach bez wywalania sobie całej zawartości _(jest też szansa, że jest to tylko problem po mojej stronie bo coś zjebałem xd)_

**Comment by kpostekk** [comment]
🫡

**Comment by kpostekk** [comment]
Dodano link do strony głównej (cf07a7845eb57188d3f705df08533d89a5e87714)
