### ISSUE TITLE
Website is randomly dropping 502 Bad Gateway on Cloudflare

### ISSUE THREAD

**Issue by rafalopilowski1** [kpostekk/caats#43]
*image for attention*
![502 HTTP cat](https://http.cat/502)

*Yes, T-Mobile is fur Deustchland*
<img width="1171" alt="image" src="https://github.com/kpostekk/caats/assets/11944411/79cca774-19a6-4c8b-b875-299a19c07157">

**Comment by kpostekk** [comment]
Deployment issue. Closed.

W dniu pt., 13.10.2023 o 15:25 Rafał Opiłowski ***@***.***>
napisał(a):

**Comment by kpostekk** [comment]
Deployment issue, unrelated.
